[package]
# TODO fix `authors` and `name` if you didn't use `cargo-generate`
name = "test-app"
edition = "2024"
version = "0.1.0"

[dependencies]
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
defmt = { version = "1", features = ["encoding-rzcobs",] }
#defmt-rtt = { version = "1.1.0", features = ["disable-blocking-mode"] }
defmt-rtt-prio = { path = "../../defmt-rtt-prio", features = ["prio_bits_4"]}
#embassy-stm32 = { git = "https://github.com/embassy-rs/embassy", features = ["stm32g474re", "dual-bank"] }
embassy-stm32 = { path = "../../embassy/embassy-stm32", features = ["stm32g474re", "dual-bank", "memory-x", "time-driver-any", "unstable-pac"] }
embassy-time = { path = "../../embassy/embassy-time", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768", "generic-queue-8"] }
full-control = { path = "../../full-control/full-control" }
load = { path = "../../load", features = ["defmt"]}
panic-probe = { version = "1", features = ["print-defmt"] }
probe-plotter = { path = "../../probe-plotter/probe-plotter" }
# TODO(4) Select the correct rtic backend
rtic = { version = "2.0.0", features = [ "thumbv7-backend" ] }
fugit = { version = "0.3.7", features = ["defmt"] }
# TODO(5) Add hal as dependency
# TODO add a monotonic if you use scheduling
# rtic-monotonics = { version = "1.0.0", features = [ "cortex-m-systick" ]}

# cargo build/run
[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true # <-
incremental = false
opt-level = "s" # <-
overflow-checks = true # <-

# cargo test
[profile.test]
codegen-units = 1
debug = 2
debug-assertions = true # <-
incremental = false
opt-level = "s" # <-
overflow-checks = true # <-

# cargo build/run --release
[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false # <-
incremental = false
lto = 'fat'
opt-level = "s" # <-
overflow-checks = false # <-

# cargo test --release
[profile.bench]
codegen-units = 1
debug = 2
debug-assertions = false # <-
incremental = false
lto = 'fat'
opt-level = "s" # <-
overflow-checks = false # <-

# uncomment this to switch from the crates.io version of defmt to its git version
# check app-template's README for instructions
# [patch.crates-io]
# defmt = { git = "https://github.com/knurling-rs/defmt", rev = "use defmt version supported by probe-rs (see changelog)" }
# defmt-rtt = { git = "https://github.com/knurling-rs/defmt", rev = "use defmt version supported by probe-rs (see changelog)" }
# defmt-test = { git = "https://github.com/knurling-rs/defmt", rev = "use defmt version supported by probe-rs (see changelog)" }
# panic-probe = { git = "https://github.com/knurling-rs/defmt", rev = "use defmt version supported by probe-rs (see changelog)" }
