name: "KiBot for half-bridge"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    paths:
      - 'half-bridge/half-bridge.kicad_sch'
      - 'half-bridge/half-bridge.kicad_pcb'
      - '.github/workflows/half-bridge.yml'
  push:
    paths:
      - 'half-bridge/half-bridge.kicad_sch'
      - 'half-bridge/half-bridge.kicad_pcb'
      - '.github/workflows/half-bridge.yml'
  pull_request:
    paths:
      - 'half-bridge/half-bridge.kicad_sch'
      - 'half-bridge/half-bridge.kicad_pcb'
      - '.github/workflows/half-bridge.yml'
  repository_dispatch:
    types: [run_qs_gha]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  quick:
    name: "Quick Start (action)"
    runs-on: ubuntu-latest

    steps:
    - name: Get repo
      uses: actions/checkout@v3
      with:
        # So we can run a diff between last 2 changes
        fetch-depth: '0'

    #- name: Run KiBot for controller
    #  # v2_k8 kibot v2 kicad v8
    #  uses: INTI-CMNB/KiBot@v2_k8
    #  with:
    #    # Required - kibot config file
    #    config: controller/config.kibot.yaml
    #    # optional - prefix to output defined in config
    #    dir: controller_
    #    # optional - schematic file
    #    schema: 'controller/controller.kicad_sch'
    #    # optional - PCB design file
    #    board: 'controller/controller.kicad_pcb'

    - name: Run KiBot for half-bridge
      uses: INTI-CMNB/KiBot@v2_k8
      with:
        # Required - kibot config file
        config: half-bridge/config.kibot.yaml
        # optional - prefix to output defined in config
        dir: half-bridge/out
        # optional - schematic file
        schema: 'half-bridge/half-bridge.kicad_sch'
        # optional - PCB design file
        board: 'half-bridge/half-bridge.kicad_pcb'

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: Automatic_outputs
        path: half-bridge/out
