name: "KiBot for half-bridge"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    paths:
      - 'half-bridge/half-bridge.kicad_sch'
      - 'half-bridge/half-bridge.kicad_pcb'
      - '.github/workflows/half-bridge.yml'
  push:
    paths:
      - 'half-bridge/half-bridge.kicad_sch'
      - 'half-bridge/half-bridge.kicad_pcb'
      - '.github/workflows/half-bridge.yml'
  pull_request:
    paths:
      - 'half-bridge/half-bridge.kicad_sch'
      - 'half-bridge/half-bridge.kicad_pcb'
      - '.github/workflows/half-bridge.yml'
  repository_dispatch:
    types: [run_qs_gha]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  quick:
    name: "Quick Start (action)"
    runs-on: ubuntu-latest

    steps:
    - name: Get repo
      uses: actions/checkout@v3
      with:
        # So we can run a diff between last 2 changes
        fetch-depth: '0'
    
    - name: Cache .cache
      uses: actions/cache@v4
      id: some-cache
      with:
        save-always: true
        path: ./.cache/
        key: some_cache

    - name: Cache 3D models data
      id: models-cache
      uses: actions/cache@v4
      with:
        save-always: true
        path: ./cache_3d
        key: cache_3d

    - run: ls -hal .
    - run: ls -hal ./.cache || echo nope
    - run: ls -hal *

    - name: Run KiBot for half-bridge
      uses: INTI-CMNB/KiBot@v2_k8
      env:
        CURRENCY: SEK
        #ELEMENT14_KEY: ${{ secrets.ELEMENT14_KEY }}
        MOUSER_KEY: ${{ secrets.MOUSER_KEY }}
        #TME_TOKEN: ${{ secrets.TME_TOKEN }}
        #TME_APP_SECRET: ${{ secrets.TME_APP_SECRET }}
        #NEXAR_CLIENT_ID: ${{ secrets.NEXAR_CLIENT_ID }}
        #NEXAR_CLIENT_SECRET: ${{ secrets.NEXAR_CLIENT_SECRET }}
      with:
        # Required - kibot config file
        config: half-bridge/config.kibot.yaml
        # optional - prefix to output defined in config
        dir: half-bridge/out
        # optional - schematic file
        schema: 'half-bridge/half-bridge.kicad_sch'
        # optional - PCB design file
        board: 'half-bridge/half-bridge.kicad_pcb'

    - run: ls -hal .
      if: always()
    - run: ls -hal ./.cache || echo nope
      if: always()
    - run: ls -hal *
      if: always()
    - run: ls -hal ./half-bridge/* || echo nope
      if: always()

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: Automatic_outputs
        path: half-bridge/out
