name: "Variants demo using GitHub actions and quick-start"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '.github/workflows/kibot.yml'
  push:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '.github/workflows/kibot.yml'
  pull_request:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '.github/workflows/kibot.yml'
  repository_dispatch:
    types: [run_qs_gha]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  quick:
    permissions:
      contents: write

    name: "Quick Start (action)"
    runs-on: ubuntu-latest

    steps:
    - name: Get repo
      uses: actions/checkout@v3
      with:
        # So we can run a diff between last 2 changes
        fetch-depth: '0'

    - name: Run KiBot
      uses: INTI-CMNB/KiBot@v2_k8
      env:
        ELEMENT14_KEY: ${{ secrets.ELEMENT14_KEY }}
        MOUSER_KEY: ${{ secrets.MOUSER_KEY }}
        TME_TOKEN: ${{ secrets.TME_TOKEN }}
        TME_APP_SECRET: ${{ secrets.TME_APP_SECRET }}
        NEXAR_CLIENT_ID: ${{ secrets.NEXAR_CLIENT_ID }}
        NEXAR_CLIENT_SECRET: ${{ secrets.NEXAR_CLIENT_SECRET }}
      with:
        quickstart: YES
      
    - name: Zip artifact
      run: zip Generated.zip ./Generated -r

    - name: Create release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: |
          Generated.zip

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: Automatic_outputs
        path: Generated